apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: pikachu
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: pikachu
  source:
    path: _apps
    repoURL: <repourl>
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
